parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.1'
        charset: utf8
        dbname:               '%env(resolve:DATABASE_NAME)%'
        host:                 '%env(resolve:DATABASE_HOST)%'
        port:                 ~
        user:                 '%env(resolve:DATABASE_USER)%'
        password:             '%env(resolve:DATABASE_PASSWORD)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Invoice/Adapter/Doctrine/config/mapping'
                prefix: 'App\Entity'
            AppDoctrine:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Invoice/Adapter/Doctrine/config/mapping/symfony/doctrine-adapter'
                prefix: 'Invoice\Adapter\Doctrine\Domain'
                alias: AppDoctrine
            Invoice:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Invoice/Adapter/Doctrine/config/mapping/symfony/domain'
                prefix: 'Invoice\Domain'
                alias: Invoice
