version: '3.4'

services:
  web:
    image: nginx:1.13.7
    depends_on:
       - php
    volumes:
     - ./docker/nginx/invoice.conf:/etc/nginx/conf.d/default.conf
     - ./public:/var/www/invoice/public
    ports:
     - "8080:80"

  php:
    image: cocoders/php-fpm:7.2.0
    volumes:
      - .:/var/www/invoice
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      POSTGRES_DSN: 'pgsql:host=postgres;port=5432;dbname=invoice;'
      POSTGRES_USER: 'invoice'
      POSTGRES_DB: 'invoice'
      POSTGRES_PASSWORD: '!E4\mP-C;Q!@2vV3'
    restart: always
    working_dir: /var/www/invoice

  postgres:
    image: postgres:10.1
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/postgres/initsql:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: '!E4\mP-C;Q!@2vV3'
      POSTGRES_USER: 'invoice'
    restart: always
    ports:
      - "5432:5432"

volumes:
  pg_data:
