Invoice\Adapter\Doctrine\Domain\User:
  type: entity
  table: users
  repositoryClass: Invoice\Adapter\Doctrine\Domain\Users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    email:
      type: string
      nullable: false
    passwordHash:
      type: string
      column: password_hash
      nullable: false
  embedded:
    address:
      class: Invoice\Domain\User\Profile
      columnPrefix: false