Invoice\Adapter\Doctrine\Domain\User:
  type: entity
  table: users
  repositoryClass: Invoice\Adapter\Doctrine\Domain\Users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    passwordHash:
      type: string
      column: password_hash
      nullable: false
  embedded:
    email:
      class: Invoice\Domain\Email
      columnPrefix: false
    profile:
      class: Invoice\Domain\User\Profile
      columnPrefix: false
      nullable: true